config/routes.rb
Myh::Application.routes.draw do  
  root to: "static_pages#home"
  resources :appointment_slots
  resources :appointments
  resources :contraceptives
  resources :gynecology_problems
  resources :gynecology_histories
  resources :contraceptive_histories
  resources :pregnancy_histories
  resources :menstrual_histories
  resources :hospitalizations
  resources :social_histories
  resources :medication_routes
  resources :medication_frequencies
  resources :vaccines
  resources :relationships
  resources :medical_histories
  resources :diseases
  resources :lab_tests
  resources :patients    
  resources :users
  resources :vital_signs
  resources :visits do
    get 'order_lab_tests', to: "visits#order_lab_tests"
  end
  resources :immunizations
  resources :visit_lab_test_xrefs
  resources :allergies
  resources :current_medications
  resources :contact_infos
  resources :insurance_infos
  resources :sessions, only: [:new, :create, :destroy]
  get "/work", to: "static_pages#work"
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  match "/signin", to: "sessions#new", via: :get
  match "/signout", to: "sessions#destroy", via: :delete
  

end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base
  belongs_to :patient
end

app/controllers/contact_infos_controller.rb
class ContactInfosController < ApplicationController
  before_action :set_contact_info, only: [:show, :edit, :update, :destroy]

  # GET /contact_infos
  # GET /contact_infos.json
  def index
    @contact_infos = ContactInfo.all
  end

  # GET /contact_infos/1
  # GET /contact_infos/1.json
  def show
  end

  # GET /contact_infos/new
  def new
    @contact_info = ContactInfo.new
  end

  # GET /contact_infos/1/edit
  def edit
  end

  # POST /contact_infos
  # POST /contact_infos.json
  def create
    @contact_info = ContactInfo.new(contact_info_params)

    respond_to do |format|
      if @contact_info.save
        format.html { redirect_to patient_path(id: @contact_info.patient_id), notice: 'Contact info was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact_info }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_infos/1
  # PATCH/PUT /contact_infos/1.json
  def update
    respond_to do |format|
      if @contact_info.update(contact_info_params)
        format.html { redirect_to patient_path(id: @contact_info.patient_id), notice: 'Contact info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_infos/1
  # DELETE /contact_infos/1.json
  # def destroy
  #   @contact_info.destroy
  #   respond_to do |format|
  #     format.html { redirect_to contact_infos_url }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_info
      @contact_info = ContactInfo.find(params[:id])
      @patient = @contact_info.patient
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_info_params
      params.require(:contact_info).permit(:patient_id, :email, :alternate_phone, :address_line1, :address_line2, :city, :province, :country, :postal_code, :emergency_contact_name, :emergency_contact_relationship, :emergency_contact_phone)
    end
end

app/helpers/contact_infos_helper.rb
module ContactInfosHelper
end

app/views/contact_infos/_contact_info.html.erb
<dl class="dl-horizontal">
	<dt>
		Email:
	</dt>
	<dd> 
		<%= @contact_info.email %>
	</dd>
	<dt>
		Alternate Phone:
	</dt>
	<dd>
		<%= @contact_info.alternate_phone %>
	</dd>
	<dt>
		Emergency Contact: 
	</dt>
	<dd>
		<%= @contact_info.emergency_contact_name %>
	</dd>
	<dt>
		Emergency Phone: 
	</dt>
	<dd> 
		<%= @contact_info.emergency_contact_phone %>
	</dd>
	<dt>
		Address Line 1: 
	</dt>
	<dd> 
		<%= @contact_info.address_line1 %>
	</dd>
	<dt>
		Address Line 2: 
	</dt>
	<dd> 
		<%= @contact_info.address_line2 %>
		<%= "-n/a-" if @contact_info.address_line2.blank? %>
	</dd>
	<dt>
		City: 
	</dt>
	<dd> 
		<%= @contact_info.city %>
	</dd>
	<dt>
		Province: 
	</dt>
	<dd> 
		<%= @contact_info.province %>
	</dd>
	<dt>
		Postal Code: 
	</dt>
	<dd> 
		<%= @contact_info.postal_code %>
	</dd>
	<dt>
		Country: 
	</dt>
	<dd> 
		<%= @contact_info.country %>
	</dd>
</dl>

app/views/contact_infos/_form.html.erb
<%= form_for @contact_info, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%#= f.label :patient_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.hidden_field :patient_id, :class => 'hidden_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :alternate_phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :alternate_phone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address_line1, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address_line1, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address_line2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address_line2, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :province, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :province, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :postal_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :postal_code, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :emergency_contact_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :emergency_contact_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :emergency_contact_relationship, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :emergency_contact_relationship, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :emergency_contact_phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :emergency_contact_phone, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                patient_path(id: @contact_info.patient.id), :class => 'btn' %>
  </div>
<% end %>

app/views/contact_infos/edit.html.erb
<%- model_class = ContactInfo -%>
<%= render partial: "common/patient_header"%>

<%= render :partial => 'form' %>

app/views/contact_infos/index.html.erb
<%- model_class = ContactInfo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:patient_id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:alternate_phone) %></th>
      <th><%= model_class.human_attribute_name(:address_line1) %></th>
      <th><%= model_class.human_attribute_name(:address_line2) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:province) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:postal_code) %></th>
      <th><%= model_class.human_attribute_name(:emergency_contact_name) %></th>
      <th><%= model_class.human_attribute_name(:emergency_contact_relationship) %></th>
      <th><%= model_class.human_attribute_name(:emergency_contact_phone) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @contact_infos.each do |contact_info| %>
      <tr>
        <td><%= link_to contact_info.id, contact_info_path(contact_info) %></td>
        <td><%= contact_info.patient_id %></td>
        <td><%= contact_info.email %></td>
        <td><%= contact_info.alternate_phone %></td>
        <td><%= contact_info.address_line1 %></td>
        <td><%= contact_info.address_line2 %></td>
        <td><%= contact_info.city %></td>
        <td><%= contact_info.province %></td>
        <td><%= contact_info.country %></td>
        <td><%= contact_info.postal_code %></td>
        <td><%= contact_info.emergency_contact_name %></td>
        <td><%= contact_info.emergency_contact_relationship %></td>
        <td><%= contact_info.emergency_contact_phone %></td>
        <td><%=l contact_info.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_contact_info_path(contact_info), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      contact_info_path(contact_info),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_contact_info_path,
            :class => 'btn btn-primary' %>

app/views/contact_infos/new.html.erb
<%- model_class = ContactInfo -%>
<%= render partial: "common/patient_header"%>
<%= render :partial => 'form' %>

app/views/contact_infos/show.html.erb
<%- model_class = ContactInfo -%>
<%= render partial: "common/patient_header"%>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @contact_info.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:alternate_phone) %>:</strong></dt>
  <dd><%= @contact_info.alternate_phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address_line1) %>:</strong></dt>
  <dd><%= @contact_info.address_line1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address_line2) %>:</strong></dt>
  <dd><%= @contact_info.address_line2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @contact_info.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:province) %>:</strong></dt>
  <dd><%= @contact_info.province %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @contact_info.country %></dd>
  <dt><strong><%= model_class.human_attribute_name(:postal_code) %>:</strong></dt>
  <dd><%= @contact_info.postal_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:emergency_contact_name) %>:</strong></dt>
  <dd><%= @contact_info.emergency_contact_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:emergency_contact_relationship) %>:</strong></dt>
  <dd><%= @contact_info.emergency_contact_relationship %></dd>
  <dt><strong><%= model_class.human_attribute_name(:emergency_contact_phone) %>:</strong></dt>
  <dd><%= @contact_info.emergency_contact_phone %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              patient_path(id: @contact_info.patient.id), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_contact_info_path(@contact_info), :class => 'btn btn-info' %>
  <!-- <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              contact_info_path(@contact_info),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %> -->
</div>