config/routes.rb
Myh::Application.routes.draw do  
  root to: "static_pages#home"
  resources :appointment_slots
  resources :appointments
  resources :contraceptives
  resources :gynecology_problems
  resources :gynecology_histories
  resources :contraceptive_histories
  resources :pregnancy_histories
  resources :menstrual_histories
  resources :hospitalizations
  resources :social_histories
  resources :medication_routes
  resources :medication_frequencies
  resources :vaccines
  resources :relationships
  resources :medical_histories
  resources :diseases
  resources :lab_tests
  resources :patients    
  resources :users
  resources :vital_signs
  resources :visits do
    get 'order_lab_tests', to: "visits#order_lab_tests"
  end
  resources :immunizations
  resources :visit_lab_test_xrefs
  resources :allergies
  resources :current_medications
  resources :contact_infos
  resources :insurance_infos
  resources :sessions, only: [:new, :create, :destroy]
  get "/work", to: "static_pages#work"
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  match "/signin", to: "sessions#new", via: :get
  match "/signout", to: "sessions#destroy", via: :delete
  

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :patient
  belongs_to :appointment
  has_many :vital_signs
  has_many :visit_lab_test_xrefs
  has_many :lab_tests, through: :visit_lab_test_xrefs
  validates :patient_id, :appointment_id,:visited_at, :visit_reason, presence: true
  validates :appointment_id, uniqueness: true
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.order("visited_at")
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @patient = Patient.find(params[:patient_id])
    @visit = @patient.visits.create( appointment_id: (params[:appointment_id]),
                          visited_at: Time.now.to_datetime, 
                          visit_reason: (params[:visit_reason]))
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)
    respond_to do |format|
      if @visit.save
        # format.html { redirect_to @patient.visits, notice: 'Visit was successfully created.' }
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @visit }
      else
        format.html { render action: 'new' }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    if params[:visit][:update_lab_tests]
      params[:visit][:lab_test_ids] ||= []
      params[:visit] = params[:visit].except(:update_lab_tests)
    end 
       
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to edit_visit_path(@visit), notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def order_lab_tests
    @visit = Visit.find(params[:visit_id])
  end
  
  # DELETE /visits/1
  # DELETE /visits/1.json
  # def destroy
  #   @visit.destroy
  #   respond_to do |format|
  #     format.html { redirect_to visits_url }
  #     format.json { head :no_content }
  #   end
  # end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_visit
    @visit = Visit.find(params[:id])
    @patient = @visit.patient
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def visit_params
    params.require(:visit).permit(:patient_id, :appointment_id, :visited_at, :visit_reason, :s_note, :o_note, 
                                  :a_note, :p_note,:update_lab_tests, :drug_allergy, :drug_interaction, 
                                  :lab_test_ids => [])
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for @visit, :html => { :class => 'form-horizontal' } do |f| %>
<% if @visit.errors.any? %>
<div class="alert">
	<h4><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h4>
	<ul>
		<% @visit.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<% f.hidden_field :patient_id, :class => 'hidden_field' %>
<% f.hidden_field :appointment_id, class: "hidden_field" %>
<% f.hidden_field :visited_at, class: "hidden_field" %>
<div class="row-fluid">
	<div class="span12">
		<div class="span4">
			<h4 class="alert alert-error">
				Visit Reason:
			</h4>
			<strong><%= simple_format(@visit.visit_reason) %></strong>
		</div>
		<div class="span4">
			<h4 class="alert alert-error">
				Summary:
			</h4>
			<% if @visit.patient.summary.blank? %>
			<p>No summary information found on record</p>
			<% else %>
			<%= simple_format(@visit.patient.summary) %>
			<% end %>
		</div>
		<div class="span4">
			<h4 class="alert alert-error">
				Alergies:
			</h4>
			<% if @visit.patient.allergies.blank? %>
			<p>No Allergies information found on record</p>
			<% else %>
			<% @visit.patient.allergies.each do | allergy |%>
			<strong><%= allergy.substance_name.titleize %>:</strong>&nbsp;
			<%= allergy.reaction.titleize %>
			<% end %>
			<% end %>
		</div>
	</div>
</div>
<div class="row-fluid">
	<%= render :partial => 'vital_signs' %>
	<%= render :partial => 'lab_tests' %>
</div>
<div class="row-fluid">
	<div class="span12">
		<h4 class="alert alert-info">
			S.O.A.P. Notes:
		</h4>
	</div>
</div>

<div class="row-fluid">
	<div class="span6">
		<div class="control-group">
			<%= f.label 'Subjective:', class: 'control-label' %>
			<div class="controls">
				<%= f.text_area :s_note, rows: 6, class: "input-xlarge" %>
			</div>
		</div>
	</div>
	<div class="span6">
		<div class="control-group">
			<%= f.label 'Objective:', class: 'control-label' %>
			<div class="controls">
				<%= f.text_area :o_note, rows: 6, class: "input-xlarge" %>
			</div>
		</div>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="span6">
			<div class="control-group">
				<%= f.label 'Assesment:', class: 'control-label' %>
				<div class="controls">
					<%= f.text_area :a_note, rows: 6, class: "input-xlarge" %>
				</div>
			</div>
		</div>
		<div class="span6">
			<div class="control-group">
				<%= f.label 'Plan:', class: 'control-label' %>
				<div class="controls">
					<%= f.text_area :p_note, rows: 6, class: "input-xlarge" %>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="form-actions">
	<%= link_to 'Back', patient_path(@visit.patient_id), class: "btn"%>
	<%= f.submit nil, :class => 'btn btn-primary' %>
	<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	patient_path(id: @visit.patient.id), :class => 'btn' %>
</div>
<% end %>

app/views/visits/_lab_tests.html.erb
<span class="span4">
	<h4 class="alert">
		Lab Tests
	</h4>
	<% if @visit.lab_tests.blank? %>
	<%= link_to 'Order Lab Tests', visit_order_lab_tests_path(@visit), class: "btn btn-small btn-primary" %>
	<% else %>
	<p>
		Ordered Lab Tests:
	</p>
	<ul class="ul-horizontal">
		<% @visit.lab_tests.each do | lab_test |%>
		<li><%= lab_test.full_name %></li>
		<% end %>
	</ul>
	<%= link_to 'Edit', visit_order_lab_tests_path(@visit), class: "btn btn-mini btn-info" %>
	<% end %>
</span>

app/views/visits/_vital_signs.html.erb
<span class="span8">
	<h4 class="alert">
		Vital Signs:&nbsp
		<%= link_to 'Add Record', new_vital_sign_path(visit_id: @visit.id), class: "btn btn-small btn-primary" %>		
	</h4>
	<% if @visit.vital_signs.blank? %>
	<p>
		No vital signs information found on record
	</p>
	<% else %>
	<table class="table table-condensed">
		<tr>
			<th>Temperature [F]</th>
			<th>Heart Rate [Per Min.]</th>
			<th>BP Systolic [HHmg]</th>
			<th>BP Diastolic [HHmg]</th>
			<th>Respiratory Rate</th>
			<th>Weight [Kg]</th>
			<th>Height [cm]</th>
			<th></th>
		</tr>
		<% @visit.vital_signs.each do | vital_sign | %>
		<tr>
			<td><%= vital_sign.temperature %></td>
			<td><%= vital_sign.heart_rate %></td>
			<td><%= vital_sign.bp_systolic %></td>
			<td><%= vital_sign.bp_diastolic %></td>
			<td><%= vital_sign.respiratory_rate %></td>
			<td><%= vital_sign.weight %></td>
			<td><%= vital_sign.height %></td>
			<td><%= link_to 'Edit', edit_vital_sign_path(vital_sign.id), class: "btn btn-mini btn-info" %></td>
		</tr>
		<% end %>
	</table>
	<% end %>
</span>

app/views/visits/edit.html.erb
<%- model_class = Visit -%>
<h4>Update <%= model_class %></h4>
<%= render partial: "common/patient_header"%>
<%= render :partial => 'form' %>

app/views/visits/index.html.erb
<%- model_class = Visit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:patient_id) %></th>
      <th><%= model_class.human_attribute_name(:visit_date) %></th>
      <th><%= model_class.human_attribute_name(:visit_reason) %></th>
      <th><%= model_class.human_attribute_name(:visit_note) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= link_to visit.patient.full_name.titleize, patient_path(visit.patient) %></td>
        <td><%= visit.visit_date %></td>
        <td><%= visit.visit_reason.titleize %></td>
        <td><%= visit.visit_note %></td>
        <td><%=l visit.updated_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_visit_path(visit), :class => 'btn btn-mini btn-info' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/visits/new.html.erb
<%- model_class = Visit -%>
<%= render partial: "common/patient_header"%>

<%= render :partial => 'form' %>

app/views/visits/order_lab_tests.html.erb
<%= form_for @visit, :html => { :class => 'form-horizontal' } do |f| %>
<% if @visit.errors.any? %>
<div class="alert">
<h4><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h4>
<ul>
	<% @visit.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
</div>
<% end %>
<div class="page-header">
  <h4>
		<span class="titlehighlight">
			<%= @visit.patient.full_name.titleize %>
		</span>
		<span class="bluehighlight">
		<%= @visit.patient.gender.titleize %>
	</span>
		<span class="titlehighlight">
			<%= @visit.patient.age %>
		</span>
		<span class="bluehighlight">
			DOB: <%= @visit.patient.date_of_birth %>
		</span>
	</h4>
</div>
	<% LabTest.all.each do |lab_test| %>
	<div class="field">
		<%= check_box_tag "visit[lab_test_ids][]", lab_test.id, @visit.lab_tests.include?(lab_test) %>
		<%= lab_test.full_name %>
	</div>
	<% end %>
	<div class="form-actions">
		<%= hidden_field "visit[update_lab_tests]", "", value: 1 %>
		<%= f.submit 'Submit Order', :class => 'btn btn-primary' %>
		<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
		edit_visit_path(id: @visit.id), :class => 'btn' %>
	</div>
<% end %>

app/views/visits/show.html.erb
<%- model_class = Visit -%>
<div class="page-header">
	<h4>
		<span class="titlehighlight">
			<%= @visit.patient.full_name.titleize %>
		</span>
		<span class="bluehighlight">
			<%= @visit.patient.gender.titleize %>
		</span>
		<span class="titlehighlight">
			<%= @visit.patient.age %>
		</span>
		<span class="bluehighlight">
			DOB:<%= @visit.patient.date_of_birth %>
		</span>
	</h4>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:visit_date) %>:</strong></dt>
  <dd><%= @visit.visited_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:visit_reason) %>:</strong></dt>
  <dd><%= @visit.visit_reason %></dd>
  <dt><strong><%= model_class.human_attribute_name(:s_note) %>:</strong></dt>
  <dd><%= @visit.s_note %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              patient_path(id: @visit.patient.id), :class => 'btn'  %>
</div>