config/routes.rb
Myh::Application.routes.draw do  
  root to: "static_pages#home"
  resources :appointment_slots
  resources :appointments
  resources :contraceptives
  resources :gynecology_problems
  resources :gynecology_histories
  resources :contraceptive_histories
  resources :pregnancy_histories
  resources :menstrual_histories
  resources :hospitalizations
  resources :social_histories
  resources :medication_routes
  resources :medication_frequencies
  resources :vaccines
  resources :relationships
  resources :medical_histories
  resources :diseases
  resources :lab_tests
  resources :patients    
  resources :users
  resources :vital_signs
  resources :visits do
    get 'order_lab_tests', to: "visits#order_lab_tests"
  end
  resources :immunizations
  resources :visit_lab_test_xrefs
  resources :allergies
  resources :current_medications
  resources :contact_infos
  resources :insurance_infos
  resources :sessions, only: [:new, :create, :destroy]
  get "/work", to: "static_pages#work"
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  match "/signin", to: "sessions#new", via: :get
  match "/signout", to: "sessions#destroy", via: :delete
  

end

app/models/visit_lab_test_xref.rb
class VisitLabTestXref < ActiveRecord::Base
  belongs_to :visit
  belongs_to :lab_test
  validates :lab_test_id, uniqueness: {scope: :visit_id}
  validates :conducted_at, presence: true, if: "received_at?"
  validates :received_at, presence: true, if: "reviewed_at?"
  validates :lab_note, presence: true, if: "received_at?"
  validate :check_received_date, if: "received_at?"
  validate :check_reviewed_date, if: "reviewed_at?"
  validate :check_conducted_date, if: "conducted_at?"
  scope :ordered, -> {where("received_at is null")}
  scope :received, -> {where("received_at is not null and reviewed_at is null")}
  scope :reviewed, -> {where("reviewed_at is not null")}
  scope :follow, -> {where("reviewed_at > '#{Date.today-21}'  and alert_flag = true and followup_complete is null")}
  def check_received_date
    self.errors.add(:received_at, "date is invalid") if received_at > Date.today
  end
  def check_reviewed_date
    self.errors.add(:reviewed_at, "date is invalid") if reviewed_at > Date.today
  end
  def check_conducted_date
    self.errors.add(:conducted_at, "date is invalid") if conducted_at > Date.today
  end
end

app/controllers/visit_lab_test_xrefs_controller.rb
class VisitLabTestXrefsController < ApplicationController
  before_action :set_visit_lab_test_xref, only: [:show, :edit, :update, :destroy]

  # GET /visit_lab_test_xrefs
  # GET /visit_lab_test_xrefs.json
  def index
    @visit_lab_test_xrefs = self.search(params[:search]) || VisitLabTestXref.ordered
    # @visit_lab_test_xrefs = VisitLabTestXref.future.order("visit_lab_test_xref_date,visit_lab_test_xref_slot_id")
  end

  # GET /visit_lab_test_xrefs/1
  # GET /visit_lab_test_xrefs/1.json
  def show
  end

  # GET /visit_lab_test_xrefs/new
  def new
  end

  # GET /visit_lab_test_xrefs/1/edit
  def edit
  end

  # POST /visit_lab_test_xrefs
  # POST /visit_lab_test_xrefs.json
  def create
  end

  # PATCH/PUT /visit_lab_test_xrefs/1
  # PATCH/PUT /visit_lab_test_xrefs/1.json
  def update
    respond_to do |format|
      if @visit_lab_test_xref.update(visit_lab_test_xref_params)
        format.html { redirect_to visit_lab_test_xrefs_path, notice: 'VisitLabTestXref was successfully updated.' }
        format.json { head :no_content }
      else
        # render 'visit_lab_test_xrefs/edit'
        format.html { render action: 'edit' }
        # format.json { render json: @visit_lab_test_xref.errors, status: :unprocessable_entity }
      end
    end
  end
  def search(search_string)
    @visit_lab_test_xrefs = 
      VisitLabTestXref.ordered.joins("inner join visits on visits.id = visit_lab_test_xrefs.visit_id 
                              inner join patients on patients.id = visits.patient_id 
                              and (patients.last_name||patients.first_name) like lower('%#{search_string}%') ").order("visit_id")
  end
  # DELETE /visit_lab_test_xrefs/1
  # DELETE /visit_lab_test_xrefs/1.json
  # def destroy
  #   @visit_lab_test_xref.destroy
  #   respond_to do |format|
  #     format.html { redirect_to visit_lab_test_xrefs_url }
  #     format.json { head :no_content }
  #   end
  # end

  private
  def set_visit_lab_test_xref
    @visit_lab_test_xref = VisitLabTestXref.find(params[:id])
    @patient = @visit_lab_test_xref.visit.patient
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def visit_lab_test_xref_params
    params.require(:visit_lab_test_xref).permit(:visit_id, :lab_test_id, :measurement, :conducted_at, :received_at,
                                                :reviewed_at, :alert_flag, :lab_note)
  end
end

app/helpers/visit_lab_test_xrefs_helper.rb
module VisitLabTestXrefsHelper
end

app/views/visit_lab_test_xrefs/_form.html.bak.erb
<%= form_for @visit_lab_test_xref, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :visit_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :visit_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lab_test_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lab_test_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :measurement, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :measurement, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :received_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :received_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reviewed_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reviewed_at, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                visit_lab_test_xrefs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/visit_lab_test_xrefs/_form.html.erb
<%= form_for @visit_lab_test_xref, :html => { class:  'form-horizontal' } do |f| %>
<% if @visit_lab_test_xref.errors.any? %>
  <div class="alert">
    <h3><%= pluralize(@visit_lab_test_xref.errors.count, "error") %> prohibited this lab test from being saved:</h3>
    <ul>
    <% @visit_lab_test_xref.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= f.hidden_field :visit_id, class: 'hidden_field' %>
<%= f.hidden_field :lab_test_id, class: 'hidden_field' %>
<div class="control-group">
	<%= f.label 'Lab Test', class: 'control-label' %>
	<div class="controls">
		<%= @visit_lab_test_xref.lab_test.full_name.titleize %>
	</div>
</div>
<div class="control-group">
	<%= f.label 'ordered at', class: 'control-label' %>
	<div class="controls">
		<%= @visit_lab_test_xref.created_at %>
	</div>
</div>
<div class="control-group">
	<%= f.label :conducted_at, class: 'control-label' %>
	<div class="controls">
		<%= f.text_field :conducted_at, class: 'datepicker', data: {date_end_date: Date.today} %>
	</div>
</div>			
<div class="control-group">
	<%= f.label :measurement, class: 'control-label' %>
	<div class="controls">
		<%= f.text_field :measurement, class: 'text_field' %>
	</div>
</div>
<div class="control-group">
	<%= f.label :received_at, class: 'control-label' %>
	<div class="controls">
		<%= f.text_field :received_at, class: 'datepicker', data: {date_end_date: Date.today} %>
	</div>
</div>
<div class="control-group">
	<%= f.label :reviewed_at, class: 'control-label' %>
	<div class="controls">
		<%= f.text_field :reviewed_at, class: 'datepicker', data: {date_end_date: Date.today} %>
	</div>
</div>
<div class="control-group">
	<%= f.label :alert_flag, class: 'control-label' %>
	<div class="controls">
		<%= f.check_box :alert_flag, class: 'check_box' %>
	</div>
</div>
<div class="control-group">
	<%= f.label :lab_note, class: 'control-label' %>
	<div class="controls">
		<%= f.text_area :lab_note, rows: 6, class: 'input-xxlarge' %>
	</div>
</div>

<div class="form-actions">
	<%= link_to 'Patient', patient_path(id: @visit_lab_test_xref.visit.patient_id), class: "btn btn-small"%>
	<%= f.submit 'Submit', class: 'btn btn-small btn-primary' %>
	<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	visit_lab_test_xrefs_path, class: 'btn btn-small' %>
</div>
<% end %>

app/views/visit_lab_test_xrefs/edit.html.erb
<%- model_class = VisitLabTestXref -%>
<%= render partial: "common/patient_header"%>
<%= render :partial => 'form' %>

app/views/visit_lab_test_xrefs/index.html.erb
<%- model_class = VisitLabTestXref -%>
<div class="page-header">
	<span>
		<%= form_tag visit_lab_test_xrefs_path, :method => 'get' do %>
		<%= search_field_tag :search, params[:search], class: "search-query" , placeholder: "patient name" %>      
		<%= submit_tag "Search", class: "btn btn-primary", :name => nil %>
		<%#= link_to "New", patients_path, class: 'btn btn-primary' %>
		<% end %>
	</span>
</div>
<div>
	<h4 class="alert alert-info">
		Lab Tests Ordered:
	</h4>
	<table class="table table-hover">
		<tr>
			<th>Patient</th>
			<th><%= model_class.human_attribute_name(:lab_test_id) %></th>
			<th><%= model_class.human_attribute_name(:conducted_at) %></th>
			<th><%= model_class.human_attribute_name(:measurement) %></th>
			<th><%= model_class.human_attribute_name(:received_at) %></th>
			<th><%= model_class.human_attribute_name(:reviewed_at) %></th>
			<th><%= model_class.human_attribute_name(:lab_note) %></th>
			<th></th>
		</tr>
		<% @visit_lab_test_xrefs.each do |visit_lab_test_xref| %>
		<tr>
			<td>
				<%= link_to visit_lab_test_xref.visit.patient.full_name.titleize, patient_path(id: visit_lab_test_xref.visit.patient_id) %>
			</td>
			<td><%= visit_lab_test_xref.lab_test.full_name.titleize %></td>
			<td><%= visit_lab_test_xref.conducted_at %></td>
			<td><%= visit_lab_test_xref.measurement %></td>
			<td><%= visit_lab_test_xref.received_at %></td>
			<td><%= visit_lab_test_xref.reviewed_at %></td>
			<td><%= visit_lab_test_xref.lab_note %></td>
			<td>
				<%= link_to "Edit", edit_visit_lab_test_xref_path(visit_lab_test_xref), :class => 'btn btn-mini btn-info' %>
			</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/visit_lab_test_xrefs/new.html.erb
<%- model_class = VisitLabTestXref -%>
<%= render partial: "common/patient_header"%>
<%= render :partial => 'form' %>

app/views/visit_lab_test_xrefs/show.html.erb
<%- model_class = VisitLabTestXref -%>
<%= render partial: "common/patient_header"%>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:visit_id) %>:</strong></dt>
  <dd><%= @visit_lab_test_xref.visit.visited_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lab_test_id) %>:</strong></dt>
  <dd><%= @visit_lab_test_xref.lab_test.full_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:conducted_at) %>:</strong></dt>
  <dd><%= @visit_lab_test_xref.conducted_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:measurement) %>:</strong></dt>
  <dd><%= @visit_lab_test_xref.measurement %></dd>
  <dt><strong><%= model_class.human_attribute_name(:received_at) %>:</strong></dt>
  <dd><%= @visit_lab_test_xref.received_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reviewed_at) %>:</strong></dt>
  <dd><%= @visit_lab_test_xref.reviewed_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lab_note) %>:</strong></dt>
  <dd><%= @visit_lab_test_xref.lab_note %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              patient_path(id: @visit_lab_test_xref.visit.patient_id), :class => 'btn'  %>
</div>