config/routes.rb
Myh::Application.routes.draw do  
  root to: "static_pages#home"
  resources :appointment_slots
  resources :appointments
  resources :contraceptives
  resources :gynecology_problems
  resources :gynecology_histories
  resources :contraceptive_histories
  resources :pregnancy_histories
  resources :menstrual_histories
  resources :hospitalizations
  resources :social_histories
  resources :medication_routes
  resources :medication_frequencies
  resources :vaccines
  resources :relationships
  resources :medical_histories
  resources :diseases
  resources :lab_tests
  resources :patients    
  resources :users
  resources :vital_signs
  resources :visits do
    get 'order_lab_tests', to: "visits#order_lab_tests"
  end
  resources :immunizations
  resources :visit_lab_test_xrefs
  resources :allergies
  resources :current_medications
  resources :contact_infos
  resources :insurance_infos
  resources :sessions, only: [:new, :create, :destroy]
  get "/work", to: "static_pages#work"
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  match "/signin", to: "sessions#new", via: :get
  match "/signout", to: "sessions#destroy", via: :delete
  

end

app/models/gynecology_problem.rb
class GynecologyProblem < ActiveRecord::Base
  has_many :gynecology_histories
end

app/controllers/gynecology_problems_controller.rb
class GynecologyProblemsController < ApplicationController
  before_action :set_gynecology_problem, only: [:show, :edit, :update, :destroy]

  # GET /gynecology_problems
  # GET /gynecology_problems.json
  def index
    @gynecology_problems = GynecologyProblem.all
  end

  # GET /gynecology_problems/1
  # GET /gynecology_problems/1.json
  def show
  end

  # GET /gynecology_problems/new
  def new
    @gynecology_problem = GynecologyProblem.new
  end

  # GET /gynecology_problems/1/edit
  def edit
  end

  # POST /gynecology_problems
  # POST /gynecology_problems.json
  def create
    @gynecology_problem = GynecologyProblem.new(gynecology_problem_params)

    respond_to do |format|
      if @gynecology_problem.save
        format.html { redirect_to @gynecology_problem, notice: 'Gynecology problem was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gynecology_problem }
      else
        format.html { render action: 'new' }
        format.json { render json: @gynecology_problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gynecology_problems/1
  # PATCH/PUT /gynecology_problems/1.json
  def update
    respond_to do |format|
      if @gynecology_problem.update(gynecology_problem_params)
        format.html { redirect_to @gynecology_problem, notice: 'Gynecology problem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gynecology_problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gynecology_problems/1
  # DELETE /gynecology_problems/1.json
  # def destroy
  #   @gynecology_problem.destroy
  #   respond_to do |format|
  #     format.html { redirect_to gynecology_problems_url }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gynecology_problem
      @gynecology_problem = GynecologyProblem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gynecology_problem_params
      params.require(:gynecology_problem).permit(:name)
    end
end

app/helpers/gynecology_problems_helper.rb
module GynecologyProblemsHelper
end

app/views/gynecology_problems/_form.html.erb
<%= form_for(@gynecology_problem) do |f| %>
  <% if @gynecology_problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gynecology_problem.errors.count, "error") %> prohibited this gynecology_problem from being saved:</h2>

      <ul>
      <% @gynecology_problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gynecology_problems/edit.html.erb
<h1>Editing gynecology_problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @gynecology_problem %> |
<%= link_to 'Back', gynecology_problems_path %>

app/views/gynecology_problems/index.html.erb
<h1>Listing gynecology_problems</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gynecology_problems.each do |gynecology_problem| %>
      <tr>
        <td><%= gynecology_problem.name %></td>
        <td><%= link_to 'Show', gynecology_problem %></td>
        <td><%= link_to 'Edit', edit_gynecology_problem_path(gynecology_problem) %></td>
        <td><%= link_to 'Destroy', gynecology_problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gynecology problem', new_gynecology_problem_path %>

app/views/gynecology_problems/new.html.erb
<h1>New gynecology_problem</h1>

<%= render 'form' %>

<%= link_to 'Back', gynecology_problems_path %>

app/views/gynecology_problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gynecology_problem.name %>
</p>

<%= link_to 'Edit', edit_gynecology_problem_path(@gynecology_problem) %> |
<%= link_to 'Back', gynecology_problems_path %>